name: CI

on:
  push:
    # Run on push to any branch
    branches: ['**']
  pull_request:
    # Run on pull request to any branch
    branches: ['**']

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    container:
      image: carlomt/geant4:11.1.2-gui

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Add Kitware APT repo and GPG key
        run: |
          mkdir -p /etc/apt/keyrings

          wget -qO - https://apt.kitware.com/keys/kitware-archive-latest.asc | \
            gpg --dearmor -o /etc/apt/keyrings/kitware.gpg

          echo "deb [signed-by=/etc/apt/keyrings/kitware.gpg] https://apt.kitware.com/ubuntu/ focal main" > /etc/apt/sources.list.d/kitware.list

          apt-get update

      - name: Install dependencies (if needed)
        run: |
          #conda install -y cmake make gxx # Add other dependencies here
          #conda clean -a
          # apt-get update
          apt-get install -y qtbase5-dev qtchooser qt5-qmake qtbase5-dev-tools
          apt-get install -y libgsl-dev libssl-dev
          export GSL_DIR=/usr
          apt-get install -y fftw3-dev
          export FFTW_DIR=/usr

          echo "GSL_DIR=$GSL_DIR" >> $GITHUB_ENV
          echo "FFTW_DIR=$FFTW_DIR" >> $GITHUB_ENV


          wget https://root.cern/download/root_v6.26.14.Linux-ubuntu22-x86_64-gcc11.4.tar.gz
          tar xvf root_v6.26.14.Linux-ubuntu22-x86_64-gcc11.4.tar.gz
          export ROOTSYS=$PWD/root/
          export ROOT_DIR=$PWD/root/

          echo "ROOTSYS=$ROOTSYS" >> $GITHUB_ENV
          echo "ROOT_DIR=$ROOT_DIR" >> $GITHUB_ENV
          
          export GEANT4_DIR=/opt/geant4/
          echo "GEANT4_DIR=$GEANT4_DIR" >> $GITHUB_ENV
          



      - name: Build project
        run: |
          export LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu/:$LD_LIBRARY_PATH
          mkdir -p build
          cd build
          cmake ..
          cmake --build . --config Release --target install

      - name: Run tests
        run: |
          cd build
          pwd; ls
          #ctest --output-on-failure
          # or replace with ./run_tests.sh or pytest